import { ConfigProvider } from "antd";
import cx from "clsx";
import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";

import "./globals.css";
import ApiProvider from "@/modules/authentication/components/ApiProvider";

const inter = Inter({ subsets: ["latin"] });

const monsterats = Montserrat({
  subsets: ["latin"],
  variable: "--font-monsterats"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cx(inter.className, monsterats.variable)}>
        <ConfigProvider theme={{ token: { colorPrimary: "#9c0c0d" } }}>
          <ApiProvider>{children}</ApiProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
